In [1]:
import pandas as pd
import numpy as np

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [3]:
df = pd.read_excel(r"C:\Users\ABC\Desktop\resume builder/database/Graphura_Cleaned_Resume_CV_data (sachin).xlsx")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [4]:
df.head()

,Sr No.,Name,Applied_Role,Email,Education,Experience,projects,Skills,Certificates
0,1,Ajit Kumar,Back-end Developer,ajit62062@gmail.com,B.COM,Fresher,"Global Sales Dashboard (Power BI), Note Taker ...","Python, SQL, MySQL, Excel, Power BI, Tableau, ...","Data Science & Analytics with AI (Itvedant), I..."
1,2,Akansha Manohar Pendorkar,Back-end Developer,akanshapendorkar96@gmail.com,B.SC,No Experience,"Student Mental Health Dashboard (Excel), SQL C...","Excel (Pivot, VLOOKUP, DAX), Power BI, MySQL, ...",Master’s in Data Science & Analytics (In Progr...
2,3,Akash Patil,Back-end Developer,aakashpatil7140@gmail.com,B.COM,3 Months,"Voice-Controlled Email System (Python), E-Lear...","Python, SQL, MySQL, Power BI, Tableau, Excel, ...","ItVedant: Excel, Power BI, MySQL, Tableau, Python"
3,4,Anchal Kasettiwar,Back-end Developer,kasettiwaranchal@gmail.com,B.TECH,6 Months,None (skills only),"MS Excel, Word, PowerPoint, Canva, Problem-sol...",NaN
4,5,Aneeka Sharma,Back-end Developer,aneekasharma767@gmail.com,B.TECH,Fresher,"Rice Recommendation (Random Forest), Car Sales...","Python (Pandas, Scikit-learn), Power BI, SQL, ...","Master in Data Science & AI (IT Vedant), IBM M..."

In [5]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 271
Columns : 9

In [6]:
print(df.columns.tolist())

['Sr No.', 'Name', 'Applied_Role', 'Email', 'Education', 'Experience', 'projects', 'Skills', 'Certificates']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sr No.        271 non-null    int64
 1   Name          271 non-null    object
 2   Applied_Role  271 non-null    object
 3   Email         271 non-null    object
 4   Education     271 non-null    object
 5   Experience    271 non-null    object
 6   projects      212 non-null    object
 7   Skills        261 non-null    object
 8   Certificates  194 non-null    object
dtypes: int64(1), object(8)
memory usage: 19.2+ KB

In [8]:
df.isnull().sum()

Sr No.           0
Name             0
Applied_Role     0
Email            0
Education        0
Experience       0
projects        59
Skills          10
Certificates    77
dtype: int64

In [9]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

In [10]:
df = df.drop_duplicates()

print("Duplicates Removed")

Duplicates Removed

In [11]:
df["Education"] = df["Education"].fillna("")
df["Experience"] = df["Experience"].fillna("")
df["projects"] = df["projects"].fillna("")
df["Skills"] = df["Skills"].fillna("")
df["Certificates"] = df["Certificates"].fillna("")

print("Missing Values Filled")

Missing Values Filled

In [13]:
df["Resume_Text"] = (
    df["Education"] + " " +
    df["Experience"] + " " +
    df["projects"] + " " +
    df["Skills"] + " " +
    df["Certificates"]
)

In [14]:
df[["Applied_Role", "Resume_Text"]].head()

         Applied_Role                                        Resume_Text
0  Back-end Developer  B.COM Fresher Global Sales Dashboard (Power BI...
1  Back-end Developer  B.SC No Experience Student Mental Health Dashb...
2  Back-end Developer  B.COM 3 Months Voice-Controlled Email System (...
3  Back-end Developer  B.TECH 6 Months None (skills only) MS Excel, W...
4  Back-end Developer  B.TECH Fresher Rice Recommendation (Random For...

In [15]:
df.to_csv("processed_resume_dataset.csv", index=False)

print("Processed Dataset Saved Successfully")

Processed Dataset Saved Successfully